---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 0.9.0
            url: quay.io/failk8s/external-dns-package:0.9.0
        url: quay.io/failk8s/external-dns-package@sha256:b9527d3280967e1bf751e011fe75607eef2f35cc655460ec024a45d297f320ca
  name: external-dns.dev.failk8s.com.0.9.0
  namespace: kapp-controller-packaging-global
spec:
  refName: external-dns.dev.failk8s.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/external-dns-package@sha256:b9527d3280967e1bf751e011fe75607eef2f35cc655460ec024a45d297f320ca
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 0.9.0
